### ISSUE TITLE
nose in maintenance mode

### ISSUE THREAD

**Issue by elveatles** [shotgunsoftware/python-api#153]
The nose testing framework is in maintenance mode according to its official [docs](http://nose.readthedocs.io/en/latest/): 

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Are there plans to switch to a different library or framework that is actively being developed?

I was planning to build unit tests based on the tests in this repository.

**Comment by thebeeland** [comment]
Hi there,

There are no plans to update the testing framework in the immediate future. If there comes a time when it becomes a necessity we'll certainly look at what our options are, but it's not a project that's currently on our roadmap.
