### ISSUE TITLE
Missing relative import

### ISSUE THREAD

**Issue by davidgaleano** [shotgunsoftware/python-api#223]
One of the imports on the embedded version of httplib2 for Python 2 was not converted to use relative imports: https://github.com/shotgunsoftware/python-api/blob/e63f83a7799982850b28494df7cef813f7d232fd/shotgun_api3/lib/httplib2/python2/__init__.py#L125

It should be `from .iri2uri import iri2uri` like in the Python 3 version.

**Comment by jfboismenu** [comment]
Hi!

We're using the sources provided by httplib2 as is as far as I know, so the code should work.

Looking at the source, file does not include a `from __future__ import absolute_import` at the top, which means that under Python 2 the importer would try to import iri2uri locally before trying to import it globally.

Is this causing an issue in your environment?

**Comment by jfboismenu** [comment]
Hi again, someone from the support team reached out to me and mentioned that your issue arose with IronPython and not CPython. We'll fork httplib2 to fix this and integrate it into our repo and submit the fix back to httplib2. I can't provide an ETA unfortunately.

Does the API appear like it's working properly once you've fixed the import?

**Comment by davidgaleano** [comment]
Hi, yes sorry I should have mentioned that this failed with IronPython. Fixing the import locally works and IronPython is able to use the API and access Shotgun without issues. Thanks.

**Comment by jfboismenu** [comment]
Hi, we've merged a fix to master and will release it shortly.
