### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by lithorus** [shotgunsoftware/python-api#38]
The API doesn't seem to be compatible with Python 3

**Comment by kporangehat** [comment]
Python 3 support will likely be driven by the overall move to it in the industry. Too many software vendors are locked into various versions of Python 2 to foresee moving to Python 3 at this point. But as movement and adoption starts to happen, we will be anticipating it and will ensure we're ahead of the curve. In the meantime, we'll still support Python 2.4-2.7 as long as we reasonably can.
