### ISSUE TITLE
mimetypes initialization fails on Windows because of TypeError

### ISSUE THREAD

**Issue by patrickwolf** [shotgunsoftware/python-api#88]
We just encounter the issue on Windows that Python 2.7 threw a TypeError on mimetypes initialization.

```
C:\Python27>python
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\Python27>python -c "import mimetypes; mimetypes.init()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\mimetypes.py", line 351, in init
    db.read_windows_registry()
  File "C:\Python27\lib\mimetypes.py", line 254, in read_windows_registry
    with _winreg.OpenKey(hkcr, subkeyname) as subkey:
TypeError: must be string without null bytes or None, not str
```

The suggested workaround is to catch the TypeError when the Shotgun API first uses mimetypes

```python
import mimetypes    # used for attachment upload
try:
    mimetypes.add_type('video/webm','.webm') # try adding to test for unicode error
except (UnicodeDecodeError, TypeError):
    # Ticket #25579 python bug on windows with unicode
    # Ticket #23371 mimetypes initialization fails on Windows because of TypeError (http://bugs.python.org/issue23371)
    # Use patched version of mimetypes
    from .lib import mimetypes as mimetypes
```
See also: mimetypes initialization fails on Windows because of TypeError (http://bugs.python.org/issue23371)

**Comment by patrickwolf** [comment]
After updating to Python 2.7.10 the issue stopped. But installs using 2.7.8 still have this issue so it should still be fixed/investigated

**Comment by kporangehat** [comment]
@patrickwolf would you mind exporting your `[HKEY_CLASSES_ROOT\MIME\Database\Content Type]` tree and emailing it to me? I'm pretty sure your fix is the way to go, but I'm unable to reproduce this as I don't have any NULLs in my registry. Would be very helpful!

**Comment by patrickwolf** [comment]
Done. Enjoy :)
