### ISSUE TITLE
Exception includes user login and password as plaintext

### ISSUE THREAD

**Issue by burninghelix123** [shotgunsoftware/python-api#91]
User password and login are included in exceptions as plain text if the shotgun_api encounters an "internal error". This seems to be used in several different functions in shotgun.py. This is obviously a huge issue when storing exceptions for debugging or when using the api in programs that automatically log to an external file. An example use of it is on line 1367 - 1382:

```python
        params.update(self._auth_params())

        except urllib2.HTTPError, e:
            if e.code == 500:
                raise ShotgunError("Server encountered an internal error. "
                    "\n%s\n(%s)\n%s\n\n" % (url, params, e))
```

Is there something i'm missing here or something I'm doing wrong?

**Comment by michaelmovies** [comment]
Lord knows no one seems to actually use the Issues functionality here, but this was closed the same day by #92.
