### ISSUE TITLE
Add package to pypi

### ISSUE THREAD

**Issue by billyshambrook** [shotgunsoftware/python-api#99]
Hey, would it be possible to get this package into pypi? 

We currently download all our other python dependencies from pypi, but with this package, we have had to fork it and upload it to our own internal pypi server. Thanks

**Comment by manneohrstrom** [comment]
Hi! If you are using `pip`, you can do `pip install git+git://github.com/shotgunsoftware/python-api.git`. Is this an option at all? For more info, see https://github.com/shotgunsoftware/python-api#installing-with-pip

I will reach out to our engineers and PMs and see what their thoughts are about pushing to pypi.

Thanks!
Manne

**Comment by taiello** [comment]
Hi, fwiw, we do the pip install approach and it works fine.  That said, we would also be in support of adding the API to pypi.

**Comment by kporangehat** [comment]
Hey guys,

We're looking into this now. There's a few things we need to sort but I think we can make it happen. Will update shortly!

cheers,
kp

**Comment by arpit1997** [comment]
@billyshambrook I agree that this package should be included or deployed to [PyPi](http://pypi.python.org)
It will be very helpful to the users and developers to install and of course it is very easy to maintain a package  on pypi so not much of a work. just a few signups, selecting the package name, develoeprs info, and some other small information is required just a 30mins of work. so You might consider this thought.
Thank you.
:smile: :smile_cat: :smile_cat:

**Comment by kporangehat** [comment]
We haven't given up on this. Our first focus along these lines was [moving our documentation to sphinx](http://developer.shotgunsoftware.com/python-api). We'll get back to this one shortly but as a reminder, in the meantime it's currently available via `pip` directly from our repo using:

```sh
pip install git+git://github.com/shotgunsoftware/python-api.git@v3.0.32
```

which is also pretty easy 😸 .

**Comment by RiceKab** [comment]
FWIW, we are running a private PyPI server locally and I just had to update the setup.py slightly to make it work. These are in my pull request (#184), although perhaps the gitignore addition is unwanted.

**Comment by nzanepro** [comment]
*bump* Please revisit this issue. it would be really fantastic to have this hosted on PyPi for CI/CD purposes.

**Comment by AWhetter** [comment]
There's a couple of things that prevent `pip install`-ing from github being a good option for us.
We don't have internet access, and so retrieving a new version is a convoluted and manual process. We can then package and upload it to our internal devpi server, but if shotgun were available on PyPi then devpi would be mirroring the shotgun on PyPi automatically and there would be no manual step required.
Even if we did have internet access, the upload to a devpi server has become a requirement to allow shotgun to be properly specified as a dependency in our packages. It used to be the case that you could specify dependencies living on github through the `dependency_link` argument to setuptools. But in newer versions of pip, that argument is now ignored (https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#dependencies-that-aren-t-in-pypi).

If it helps, there's Github Actions available to automate the process of releasing to PyPi when a tagged commit is pushed: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by michaelkozakovsc** [comment]
Bump! My org doesn't allow requirements.txt files with git links, so would really appreciate a pypi distribution!

**Comment by AWhetter** [comment]
I've started uploading shotgun to PyPI myself (https://pypi.org/project/shotgun-api3/) from https://github.com/AWhetter/shotgun_api3. I'll happily give upload permissions to the shotgun team if they would like to manage these uploads themselves.

**Comment by darkvertex** [comment]
@AWhetter care to refresh it? it's a couple of releases behind.

**Comment by carlos-villavicencio-adsk** [comment]
Hello folks. Unfortunately, we don't have plans to have the packages available on PyPi at this point. Sorry if this causes any inconvenience.

**Comment by AWhetter** [comment]
@darkvertex Thanks for the reminder. I've uploaded the most recent versions.

**Comment by AWhetter** [comment]
@nrusch Thanks for the reminder. I've uploaded v3.9.0.

**Comment by nrusch** [comment]
Oh great, thank you for the quick response!
